/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package gui;

import DAO.UserDao;
import action.SetTime;
import command.Commands;
import java.io.IOException;
import java.net.InetAddress;
import java.net.Socket;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model_structure.Global;
import model_structure.define;


public class RechargeGui extends javax.swing.JFrame {
    UserDao userDao = new UserDao();
  
    public RechargeGui() {
        initComponents();
        this.setLocationRelativeTo(null);
        username.setText(Global.username);
        phone.setText(Global.phone);
        sotienhientai.setText(Global.sotienconlai);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sotien = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        capnhatbtn = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        money = new javax.swing.JTextField();
        sotienhientai = new javax.swing.JTextField();
        muoik = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        muoik1 = new javax.swing.JButton();
        muoik2 = new javax.swing.JButton();
        muoik3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 3));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(329, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 51));
        jLabel1.setText("RECHARGE");

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/icon-X.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setMargin(null);
        jButton1.setMaximumSize(new java.awt.Dimension(41, 39));
        jButton1.setMinimumSize(new java.awt.Dimension(41, 39));
        jButton1.setName(""); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(41, 39));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Tên đăng nhập");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Số điện thoại");

        sotien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sotien.setForeground(new java.awt.Color(102, 0, 102));
        sotien.setText("Số tiền nạp( VNĐ )");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("Số tiền hiện tại");

        capnhatbtn.setBackground(new java.awt.Color(153, 255, 255));
        capnhatbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        capnhatbtn.setText("Nạp tiền");
        capnhatbtn.setActionCommand("");
        capnhatbtn.setHideActionText(true);
        capnhatbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capnhatbtnActionPerformed(evt);
            }
        });

        username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username.setFocusable(false);
        username.setPreferredSize(new java.awt.Dimension(120, 20));

        phone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        phone.setFocusable(false);
        phone.setPreferredSize(new java.awt.Dimension(120, 20));

        money.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        money.setForeground(new java.awt.Color(204, 0, 0));
        money.setPreferredSize(new java.awt.Dimension(120, 20));
        money.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyActionPerformed(evt);
            }
        });

        sotienhientai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sotienhientai.setForeground(new java.awt.Color(255, 0, 51));
        sotienhientai.setFocusable(false);
        sotienhientai.setPreferredSize(new java.awt.Dimension(120, 20));

        muoik.setBackground(new java.awt.Color(255, 204, 204));
        muoik.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        muoik.setText("10.000");
        muoik.setToolTipText("");
        muoik.setFocusable(false);
        muoik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muoikActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("20.000");
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 153, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("30.000");
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        muoik1.setBackground(new java.awt.Color(255, 102, 153));
        muoik1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        muoik1.setText("100.000");
        muoik1.setToolTipText("");
        muoik1.setFocusable(false);
        muoik1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muoik1ActionPerformed(evt);
            }
        });

        muoik2.setBackground(new java.awt.Color(102, 255, 255));
        muoik2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        muoik2.setText("50.000");
        muoik2.setToolTipText("");
        muoik2.setFocusable(false);
        muoik2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muoik2ActionPerformed(evt);
            }
        });

        muoik3.setBackground(new java.awt.Color(255, 102, 102));
        muoik3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        muoik3.setText("200.000");
        muoik3.setToolTipText("");
        muoik3.setFocusable(false);
        muoik3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muoik3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(sotien, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sotienhientai, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(money, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(muoik2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(muoik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(muoik1, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(26, 26, 26)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(muoik3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                                    .addGap(26, 26, 26)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(capnhatbtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sotienhientai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(muoik, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(muoik1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(muoik2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(muoik3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sotien, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(money, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(capnhatbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void capnhatbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capnhatbtnActionPerformed
        String username=Global.username;
        String sotienstr= money.getText();
        String status=Global.status;
        int row=0;
        String iprow="";
                    if(!status.equals("ONLINE"))
                    {
                        long sotien = Long.parseLong(sotienstr);
                        int heso=(int)(Global.cost/60);
                        long time = (long)(sotien/heso)*60;// 12k == 1h
                        long timeavailable = userDao.gettimeUser(username);
                        time= time+timeavailable;
                        userDao.settimeuser(username, time);
                        JOptionPane.showMessageDialog(null, "Nạp tiền thành công!");
                        Global.mainGui.settableuser();
                    }
                       // nếu tài khoản đang online
                    if(status.equals("ONLINE"))
                    {
                        
                        Socket socket = null;
                        try
                        {
                            
                            
                            for(int i=0; i<Global.numpc;i++)
                            { 
                                String name=(String) Global.mainGui.main_table.getValueAt(i, 3);
                                if(name!=null)
                                {
                                    if(name.equals(username))
                                    {
                                        row=i;
                                        iprow=(String) Global.mainGui.main_table.getValueAt(i, 1);
                                        break;
                                    }
                                }   
                            }
                            Global.threadtime[row].stopThread();
                            long sotien = Long.parseLong(sotienstr);
                            int heso=(int)(Global.cost/60);
                            long time = (long)(sotien/heso)*60;// 12k == 1h
                            long timeavailable = Global.time[row];
                            time= time+timeavailable;
                            userDao.settimeuser(username, time);
                            
                            
                            InetAddress ipclient = InetAddress.getByName(iprow);
                            socket = new Socket(ipclient, define.CMD_CLIENT_PORT);
                            Commands cmd = new Commands(socket);
                            Calendar startCal = Calendar.getInstance();
                            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
                            String startTime = sdf.format(startCal.getTime());
                            long start = startCal.getTimeInMillis();
                            boolean flag = cmd.recharge();
                            if(flag == true)
                            {
                                Global.mainGui.main_table.setValueAt(iprow, row, 1);
                                Global.mainGui.main_table.setValueAt(define.ONLINE, row, 2);
                                Global.mainGui.main_table.setValueAt(username, row, 3);
                                Global.mainGui.main_table.setValueAt(startTime, row, 4);
                                
                                SetTime setTime = new SetTime(start, row, userDao.gettimeUser(username),username);
                                setTime.start();
                                Global.threadtime[row] = setTime;// đưa vao mang idclient hàng số mấy 
                            }
                            socket.close();
                        }catch(Exception e)
                        {
                            e.printStackTrace();
                        }
                        JOptionPane.showMessageDialog(null, "Nạp tiền thành công!");
                        Global.mainGui.settableuser();
            try {
                socket.close();
            } catch (IOException ex) {
                Logger.getLogger(RechargeGui.class.getName()).log(Level.SEVERE, null, ex);
            }
                    }  
                    
                    this.dispose();
    }//GEN-LAST:event_capnhatbtnActionPerformed

    private void moneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyActionPerformed

    private void muoikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muoikActionPerformed
        money.setText("10000");
        this.setVisible(true);
    }//GEN-LAST:event_muoikActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        money.setText("20000");
        this.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        money.setText("30000");
        this.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void muoik2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muoik2ActionPerformed
        money.setText("50000");
        this.setVisible(true);
    }//GEN-LAST:event_muoik2ActionPerformed

    private void muoik1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muoik1ActionPerformed
        money.setText("100000");
        this.setVisible(true);
    }//GEN-LAST:event_muoik1ActionPerformed

    private void muoik3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muoik3ActionPerformed
        money.setText("200000");
        this.setVisible(true);
    }//GEN-LAST:event_muoik3ActionPerformed
    public long changemoneytolongtime(String sotienString)
    {
        long time=0;
        String[] parts = sotienString.split(" ");
        float money =Float.parseFloat(parts[0]);
        float heso=((Global.cost/60f)/1000f);
        int minute = (int) (money/(heso)); //12k/1h
        time= minute*60;
        return time;
    }
            
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton capnhatbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField money;
    private javax.swing.JButton muoik;
    private javax.swing.JButton muoik1;
    private javax.swing.JButton muoik2;
    private javax.swing.JButton muoik3;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel sotien;
    private javax.swing.JTextField sotienhientai;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

}
